// 更新用户信息
const UPDATE_AUTH = 'UPDATE_AUTH'

// 清除用户信息
const CLEAN_AUTH = 'CLEAN_AUTH'
// 用户列表
const UPDATE_ENTERPRISESIMPLE = 'UPDATE_ENTERPRISESIMPLE'
export { UPDATE_AUTH, CLEAN_AUTH, UPDATE_ENTERPRISESIMPLE }
